# Generated by Django 4.2.5 on 2023-10-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesense', '0002_timeunit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='TimeRecord',
        ),
    ]
