# Generated by Django 4.2.5 on 2023-10-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesense', '0003_rename_record_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='timesense.timeunit'),
        ),
    ]
