# Generated by Django 4.2.5 on 2023-10-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesense', '0004_timerecord_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
