# Generated by Django 4.2.5 on 2023-10-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesense', '0005_timeunit_abbreviation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerecord',
            old_name='actual',
            new_name='actual_ms',
        ),
        migrations.RenameField(
            model_name='timerecord',
            old_name='start',
            new_name='start_epoch_ms',
        ),
        migrations.RenameField(
            model_name='timerecord',
            old_name='stop',
            new_name='stop_epoch_ms',
        ),
        migrations.RenameField(
            model_name='timerecord',
            old_name='target',
            new_name='target_ms',
        ),
        migrations.AddField(
            model_name='timeunit',
            name='conversion_to_ms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
