# Generated by Django 4.2.5 on 2023-10-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesense', '0006_rename_actual_timerecord_actual_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='actual_ms',
            field=models.IntegerField(null=True),
        ),
    ]
