# Generated by Django 4.2.5 on 2023-10-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesense', '0009_alter_timerecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='timezone',
            field=models.SmallIntegerField(default=0),
        ),
    ]
