# Generated by Django 4.2.5 on 2023-10-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesense', '0010_timerecord_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerecord',
            old_name='timezone',
            new_name='timezone_offset',
        ),
    ]
